### ISSUE TITLE
epic

### ISSUE THREAD

**Issue by Hansanghyeon** [Hansanghyeon/datarize-fe-assignments#1]
재미있는 프로젝트 🥕
하고싶은거 다하자

## backend

- [ ] [BE] 배포환경 구성
- [ ] [BE] customers, products, purchases 스키마 구성하기
- [ ] [BE] Graphql server 구성
- [ ] [BE] `apps/backend/src/data/*.json` 해당 스키마를 기준으로 대용량 데이터를 만들기.
- [ ] [BE] Seed 기능 추가하기 (로그인한 유저만 가능하도록) (실시간 데이터 주입)
	- [ ] [BE] 실시간 데이터주입 Elixir 테스트해보기 - job의 기능 (option)

### 개발목표

- Fastify
	- Hasura의 Actions와 Remote Schemas를 통해 GraphQL 요청을 처리, 웹훅 처리
		- 커스텀 GrpahQL 리졸버처리
		- Hsura의 action 요청처리
		- Event Trigger를 통한 비즈니스 로직실행
			- 비즈니스로직을 Harsura 데이터를 가져와처리하고 schema를 사용하는 방향
		- Webhook 엔드포인트 제공
- 인증
	- OAuth2.0 도입하지 않는다. auth 가드 만들지 않는다.
	- Hasura + clerk를 이용
- 데이터 레이어
	- graphql을 숙련하기 위해서 hasura를 사용
	- 
	- Hasura + clerk 추가
	- fly.io 배포환경 테스트 (hasura + pg)
		- fly.io하기전까지는 self-host로 테스트 dfa.api.toy.hyeon.pro (dfa = datarize-fe-assignments)

## frontend

반응형 - 맥북 14인치에서 원활하게 볼 수있는 화면을 구현한뒤에 모바일에서 원활하게 볼 수있는 환경구축

- [ ] [FE] 배포환경구성
- HomePage - **쇼핑몰 구매 데이터 대시보드 애플리케이션**
	- **가격대별 구매 빈도 차트**
	- **가장 많이 구매한 고객 목록 및 검색 기능**
	- [ ] [FE] Chart 추가
	- [ ] [FE] table 추가
	- [ ] [FE] table

### 개발목표

- graphql + relay 맛보기 특히 relay fragment 익숙해져보기 (상세보기 뷰를 노션처럼 구현 -> 목록과 상세의 fragment!)
- tailwindcss v4 연습하기 + daisyui v5 테스트

**Comment by Hansanghyeon** [comment]
2024-12-05

FN seed기능에서 대용량 제품명데이터를 허깅스페이스에서 가져오는 방법에서 막혔다. faker.js를 사용할수있겠지만 10만개? 100만개 정도 만든다할때 허길스페이스의 데이터셋을 이용하는게 더 좋을것같다 생각해서 시도하고있는데 막히는 부분이 많다.

**Comment by Hansanghyeon** [comment]
2024-12-05T21:02:53+09:00

**Comment by Hansanghyeon** [comment]
|    | start | end |
| -- | ----- | --- |
| 출근길 | 2024-12-06T09:52:44+09:00 | - |

**Comment by Hansanghyeon** [comment]
|    | start | end |
| -- | ----- | --- |
| 출근길 | 2024-12-10T21:04:34+09:00 | - |

**Comment by Hansanghyeon** [comment]
|    | start | end |
| -- | ----- | --- |
| 출근길 | 2024-12-11T08:05:10+09:00 | - |

**Comment by Hansanghyeon** [comment]
|    | start | end |
| -- | ----- | --- |
| 🚇 출근길 | 2024-12-13T10:00:41+09:00 | - |

**Comment by Hansanghyeon** [comment]
|    | start | end | progress-time |
| -- | ----- | --- | ------------- |
| 🚇 퇴근길 | 2024-12-13T10:00:41+09:00 | - | - |
